- name: Copy Inception service file
  template:
    src: templates/inception.service.j2
    dest: /etc/systemd/system/inception.service
    mode: 0644

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable Inception service
  systemd:
    name: inception
    enabled: yes
