---
# tasks file for roles/inception

- name: Copy project files to the remote host
  synchronize:
    src: inception/
    dest: "{{ ansible_env.HOME }}/project"
    recursive: yes

- name: make all
  shell: |
    make -C "{{ ansible_env.HOME }}/project" all

- name: Start Docker Compose
  docker_compose:
    project_src: "{{ ansible_env.HOME }}/project/srcs"
    state: present
    build: yes
    # detached: yes
