- name: cloud-1
  hosts: all
  become: yes
  tasks:
  - name: Install pip3
    become: true
    apt:
      name: python3-pip
      state: present

  - name: Install docker-compose
    pip:
      name: docker-compose

  - name: Copy project files to the remote host
    synchronize:
      src: inception/
      dest: /root/project
      recursive: yes

  # - name: Install Docker and Docker Compose
  #   apt:
  #     name:
  #       - docker.io
  #       - docker-compose
  #     state: present

  - name: make all
    shell: |
      make -C /root/project all

  - name: Start Docker Compose
    docker_compose:
      project_src: /root/project/srcs
      state: present
      build: yes
      # detached: yes
