- name: cloud-1
  hosts: all
  become: yes
  tasks:
  - name: Install pip3
    become: true
    apt:
      name: python3-pip
      state: present

  - name: Install docker-compose
    pip:
      name: docker-compose

  - name: Copy project files to the remote host
    synchronize:
      src: inception/
      dest: /root/project
      recursive: yes

  - name: make all
    shell: |
      make -C /root/project all

  # - name: Start Docker Compose
  #   docker_compose:
  #     project_src: /root/project/srcs
  #     state: present
  #     restart_policy: always
  #     build: yes
  #     # detached: yes

  - name: Create Docker Compose systemd service file
    template:
      src: docker-compose.service.j2
      dest: /etc/systemd/system/docker-compose.service
    notify:
      - Reload systemd

  - name: Enable and start Docker Compose systemd service
    systemd:
      name: docker-compose.service
      enabled: true
      state: started

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes
