version: '3'

services:

  mariadb:
    container_name: "mariadb"
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        - MARIADB_ROOT_PWD
        - MARIADB_DB
        - MARIADB_USER
        - MARIADB_PWD
    ports:
      - "3306:3306"
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - back
    restart: on-failure

  nginx:
    container_name: "nginx"
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443" #https default port
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - front
    restart: on-failure

  wordpress:
    container_name: "wordpress"
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
      args:
        - MARIADB_ROOT_PWD
        - MARIADB_DB
        - MARIADB_USER
        - MARIADB_PWD
        - WP_URL
        - WP_DATABASE
        - WP_TITLE
        - WP_ADMIN_USER
        - WP_ADMIN_PWD
        - WP_ADMIN_EMAIL
        - WP_USER
        - WP_USER_PWD
        - WP_USER_EMAIL
    ports:
      - "9000:9000" #https default port
    volumes:
      - wordpress_volume:/var/www/wordpress
    environment:
      - WP_URL=${WP_URL}
      - WP_DATABASE=${WP_DATABASE}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_PWD=${WP_USER_PWD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PWD=${MARIADB_PWD}
      - MARIADB_DB=${MARIADB_DB}
      - TABLE_PREFIX=${TABLE_PREFIX}
    networks:
      - back
      - front
    restart: always

  phpmyadmin:
    build:
      context: ./requirements/phpmyadmin/
      dockerfile: Dockerfile
    networks:
      - front
      - back
    ports:
      - "9999:9999"
    restart: on-failure


# https://medium.com/@alexanderyegorov_67403/docker-volumes-changes-in-compose-version-3-95a7c48f6d17
volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      device: ${HOME}/data/database
      type: none
      o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      device: ${HOME}/data/wordpress
      type: none
      o: bind

networks:
  front:
  back:
