Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/jammy64"
	config.vm.hostname = "vagrant"
	config.vm.box_url = "ubuntu/jammy64"
	config.vm.network "private_network", ip: "192.168.56.10"
	config.vm.provider "virtualbox" do |vb|
	  vb.name = "vagrant"
	  vb.memory = "8192"
	  vb.cpus = 8
	end
  end
