# - name: my first playbook
#   hosts: all
#   tasks:
#   # 1. (watch out for the src path)
#   #
#   # - name: a simple copy
#   #   copy:
#   #     src: test.txt
#   #     dest: /tmp/sucho.txt

#   # 2.
#   #
#   # 'mkdir -p tmp/sucho/{1,2,3}'
#   # - name: a simple compy
#   #   copy:
#   #     src: tmp/
#   #     dest: /tmp/

#   # 3. (like mv)
#   # - name: create example file
#   #   file:
#   #     path: /home/scho/my_example_file.txt
#   #     state: touch

#   # - name: copy
#   #   copy:
#   #     src: /home/scho/my_example_file.txt
#   #     dest: /tmp/
#   #     remote_src: yes

- name: my first playbook
  hosts: all
  # 4.
  # vars:
  #   myfiles:
  #     - { source: "sucho1.txt", destination: "/tmp/{{ ansible_hostname }}_sucho1.txt", permission: "0755" }
  #     - { source: "sucho1.txt", destination: "/home/scho/{{ ansible_hostname }}_sucho2.txt", permission: "0644" }
  # tasks:
  # - name: copy
  #   copy:
  #     src: "tmp/{{ item.source }}"
  #     dest: "{{ item.destination }}"
  #     mode: "{{ item.permission }}"
  #   with_items: "{{ myfiles }}"
  # 5.
  # tasks:
  # - name: copy
  #   copy:
  #     src: "{{ item }}"
  #     dest: /tmp/
  #     backup: yes # for creating backup
  #   with_fileglob:
  #   - tmp/such*.*
  tasks:
  # 6.
  # - name: copy
  #   copy:
  #     content: |
  #       hi
  #       sucho.
  #       hello world we are on {{ ansible_hostname }}
  #     dest: /tmp/hello.txt

  # 7.
  # - name: copie du fichier nginx.conf avec check
  #   copy:
  #     src: nginx.conf
  #     dest: /etc/nginx/nginx.conf
  #     owner: root
  #     group: root
  #     mode: 0644
  #     validate: /usr/bin/nginx -t -c %s
  - name: Add devops user to the sudoers
    copy:
      dest: "/etc/sudoers.d/devops"
      content: "scho ALL=(ALL)  NOPASSWD: ALL"
      owner: root
      group: root
      mode: 0400
      validate: /usr/sbin/visudo -cf %s
    become: yes
