- name: our local server
  connection: local
  hosts: localhost
  become: yes
  tasks:
  - name: install nginx
    apt:
      name: nginx
      update_cache: yes
      state: present

  - name: start nginx server
    systemd:
      name: nginx
      state: started

  - name: clean
    file:
      path: "{{ item }}"
      state: absent
    with_fileglob:
    - /var/www/html/*.html

- name: get hosts and store it
  hosts: all
  tasks:
  - name: fetch
    fetch:
      src: /etc/hosts
      dest: /var/www/html/hosts_{{ ansible_hostname }}.txt
      flat: yes


# - name: my first playbook
#   hosts: all
#   tasks:

# # 1.
#   # - name: use the fetch module
#   #   fetch:
#   #     src: /etc/hosts
#   #     dest: collect/

# #2.
#   # - name: fetch
#   #   fetch:
#   #     src: /etc/hosts
#   #     dest: collect/hosts_{{ ansible_hostname }}.txt

#   # 3. using flat
#   - name: fetch
#     fetch:
#       src: /etc/hosts
#       dest: collect/hosts_{{ ansible_hostname }}.txt
#       flat: yes
