- name: Docker installation
  become: yes
  block:
    - name: Install docker on the target host
      include_tasks: installation.yml
    - name: Post installation setup for docker to be run without sudo command
      when: current_user != 'root'
      include_tasks: post_installation.yml
