- name: my first playbook
  hosts: all
  become: yes
  vars:
    nginx_port: 6666
  tasks:
  - name: install nginx
    apt:
      name: nginx, curl
      state: present
      cache_valid_time: 3600
      update_cache: yes

  - name: start nginx
    service:
      name: nginx
      state: started

  - name: remove default file
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - "/etc/nginx/sites-available/default"
    - "/etc/nginx/sites-enabled/default"

  - name: install vhost
    template:
      src: default_vhost.conf.j2
      dest: /etc/nginx/sites-available/default_vhost.conf
      owner: root
      group: root
      mode: 0644
    notify: reload_nginx # handler name

  - name: flush_handlers
    meta: flush_handlers

  - name: activate vhost
    file:
      src: /etc/nginx/sites-available/default_vhost.conf
      dest: /etc/nginx/sites-enabled/default_vhost.conf
      state: link

  # example
  # - name: Check if need to restart
  #   stat:
  #     path: /var/run/reboot.pending
  #   register: __need_reboot
  #   changed_when: __need_reboot.stat.exists
  #   notify: reboot_server

  handlers:
  - name: reload_nginx
    systemd:
      name: nginx
      state: reloaded
